"""expand daily entry with mood, habits, supplements

Revision ID: 1768d5271c00
Revises: b13e083e480a
Create Date: 2026-03-30 14:15:47.111372

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1768d5271c00"
down_revision: str | Sequence[str] | None = "b13e083e480a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("daily_entries", sa.Column("mood_score", sa.Integer(), nullable=True))
    op.add_column("daily_entries", sa.Column("mood_emotions", sa.Text(), nullable=True))
    op.add_column("daily_entries", sa.Column("stress_source", sa.String(length=50), nullable=True))
    op.add_column(
        "daily_entries",
        sa.Column("activity_pain_effect", sa.String(length=20), nullable=True),
    )
    op.add_column("daily_entries", sa.Column("alcohol", sa.Boolean(), nullable=True))
    op.add_column("daily_entries", sa.Column("heavy_dinner", sa.Boolean(), nullable=True))
    op.add_column("daily_entries", sa.Column("omega3", sa.Boolean(), nullable=True))
    op.add_column("daily_entries", sa.Column("vitamin_d", sa.Boolean(), nullable=True))
    op.add_column("daily_entries", sa.Column("magnesium", sa.Boolean(), nullable=True))
    op.add_column("daily_entries", sa.Column("turmeric", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("daily_entries", "turmeric")
    op.drop_column("daily_entries", "magnesium")
    op.drop_column("daily_entries", "vitamin_d")
    op.drop_column("daily_entries", "omega3")
    op.drop_column("daily_entries", "heavy_dinner")
    op.drop_column("daily_entries", "alcohol")
    op.drop_column("daily_entries", "activity_pain_effect")
    op.drop_column("daily_entries", "stress_source")
    op.drop_column("daily_entries", "mood_emotions")
    op.drop_column("daily_entries", "mood_score")
    # ### end Alembic commands ###
