"""drop mood, stress, activity, nutrition tables

Revision ID: 6247613924fc
Revises: 1768d5271c00
Create Date: 2026-03-30 15:00:24.741243

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6247613924fc"
down_revision: str | Sequence[str] | None = "1768d5271c00"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_mood_records_entry_id"), table_name="mood_records")
    op.drop_table("mood_records")
    op.drop_index(op.f("ix_stress_records_entry_id"), table_name="stress_records")
    op.drop_table("stress_records")
    op.drop_index(op.f("ix_activity_records_entry_id"), table_name="activity_records")
    op.drop_table("activity_records")
    op.drop_index(op.f("ix_nutrition_records_entry_id"), table_name="nutrition_records")
    op.drop_table("nutrition_records")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nutrition_records",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("entry_id", sa.INTEGER(), nullable=False),
        sa.Column("meals", sa.TEXT(), nullable=True),
        sa.Column("alcohol", sa.BOOLEAN(), nullable=True),
        sa.Column("caffeine_cups", sa.INTEGER(), nullable=True),
        sa.Column("water_liters", sa.FLOAT(), nullable=True),
        sa.Column("notes", sa.TEXT(), nullable=True),
        sa.ForeignKeyConstraint(
            ["entry_id"],
            ["daily_entries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_nutrition_records_entry_id"), "nutrition_records", ["entry_id"], unique=False
    )
    op.create_table(
        "activity_records",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("entry_id", sa.INTEGER(), nullable=False),
        sa.Column("type", sa.VARCHAR(length=50), nullable=False),
        sa.Column("duration_min", sa.INTEGER(), nullable=True),
        sa.Column("pain_effect", sa.VARCHAR(length=20), nullable=True),
        sa.Column("notes", sa.TEXT(), nullable=True),
        sa.ForeignKeyConstraint(
            ["entry_id"],
            ["daily_entries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_activity_records_entry_id"), "activity_records", ["entry_id"], unique=False
    )
    op.create_table(
        "stress_records",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("entry_id", sa.INTEGER(), nullable=False),
        sa.Column("level", sa.INTEGER(), nullable=False),
        sa.Column("source", sa.VARCHAR(length=50), nullable=True),
        sa.Column("notes", sa.TEXT(), nullable=True),
        sa.ForeignKeyConstraint(
            ["entry_id"],
            ["daily_entries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_stress_records_entry_id"), "stress_records", ["entry_id"], unique=False
    )
    op.create_table(
        "mood_records",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("entry_id", sa.INTEGER(), nullable=False),
        sa.Column("score", sa.INTEGER(), nullable=False),
        sa.Column("emotions", sa.TEXT(), nullable=True),
        sa.Column("notes", sa.TEXT(), nullable=True),
        sa.ForeignKeyConstraint(
            ["entry_id"],
            ["daily_entries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_mood_records_entry_id"), "mood_records", ["entry_id"], unique=False)
    # ### end Alembic commands ###
