"""add health expansion nutrition import and workout tables

Revision ID: 6ff20dd30eda
Revises: 794f9d2b706f
Create Date: 2026-03-28 19:10:18.463853

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6ff20dd30eda"
down_revision: str | Sequence[str] | None = "794f9d2b706f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nutrition_import_records",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("entry_id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("calories_kj", sa.Float(), nullable=True),
        sa.Column("protein_g", sa.Float(), nullable=True),
        sa.Column("carbs_g", sa.Float(), nullable=True),
        sa.Column("fat_total_g", sa.Float(), nullable=True),
        sa.Column("fat_saturated_g", sa.Float(), nullable=True),
        sa.Column("fiber_g", sa.Float(), nullable=True),
        sa.Column("sugar_g", sa.Float(), nullable=True),
        sa.Column("water_ml", sa.Float(), nullable=True),
        sa.Column("caffeine_mg", sa.Float(), nullable=True),
        sa.Column("sodium_mg", sa.Float(), nullable=True),
        sa.Column("potassium_mg", sa.Float(), nullable=True),
        sa.Column("magnesium_mg", sa.Float(), nullable=True),
        sa.Column("calcium_mg", sa.Float(), nullable=True),
        sa.Column("iron_mg", sa.Float(), nullable=True),
        sa.Column("zinc_mg", sa.Float(), nullable=True),
        sa.Column("cholesterol_mg", sa.Float(), nullable=True),
        sa.Column("vitamin_a_mcg", sa.Float(), nullable=True),
        sa.Column("vitamin_c_mg", sa.Float(), nullable=True),
        sa.Column("vitamin_d_mcg", sa.Float(), nullable=True),
        sa.Column("vitamin_e_mg", sa.Float(), nullable=True),
        sa.Column("vitamin_k_mcg", sa.Float(), nullable=True),
        sa.Column("vitamin_b6_mg", sa.Float(), nullable=True),
        sa.Column("vitamin_b12_mcg", sa.Float(), nullable=True),
        sa.Column("folate_mcg", sa.Float(), nullable=True),
        sa.Column("niacin_mg", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["entry_id"],
            ["daily_entries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_nutrition_import_records_entry_id"),
        "nutrition_import_records",
        ["entry_id"],
        unique=False,
    )
    op.create_table(
        "workout_records",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("entry_id", sa.Integer(), nullable=False),
        sa.Column("workout_type", sa.String(length=100), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=True),
        sa.Column("end_time", sa.DateTime(), nullable=True),
        sa.Column("duration_min", sa.Float(), nullable=True),
        sa.Column("active_energy_kj", sa.Float(), nullable=True),
        sa.Column("intensity", sa.Float(), nullable=True),
        sa.Column("max_hr", sa.Integer(), nullable=True),
        sa.Column("avg_hr", sa.Integer(), nullable=True),
        sa.Column("distance_km", sa.Float(), nullable=True),
        sa.Column("steps", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["entry_id"],
            ["daily_entries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_workout_records_entry_id"), "workout_records", ["entry_id"], unique=False
    )
    op.create_index(
        op.f("ix_activity_records_entry_id"), "activity_records", ["entry_id"], unique=False
    )
    op.add_column("apple_health_records", sa.Column("sleep_rem_hours", sa.Float(), nullable=True))
    op.add_column("apple_health_records", sa.Column("distance_km", sa.Float(), nullable=True))
    op.add_column("apple_health_records", sa.Column("flights_climbed", sa.Integer(), nullable=True))
    op.add_column("apple_health_records", sa.Column("resting_energy_kj", sa.Float(), nullable=True))
    op.add_column(
        "apple_health_records", sa.Column("exercise_intensity", sa.Float(), nullable=True)
    )
    op.add_column("apple_health_records", sa.Column("walking_hr_avg", sa.Integer(), nullable=True))
    op.add_column("apple_health_records", sa.Column("vo2_max", sa.Float(), nullable=True))
    op.add_column("apple_health_records", sa.Column("cardio_recovery", sa.Float(), nullable=True))
    op.add_column("apple_health_records", sa.Column("step_length_cm", sa.Float(), nullable=True))
    op.add_column(
        "apple_health_records", sa.Column("walking_asymmetry_pct", sa.Float(), nullable=True)
    )
    op.add_column(
        "apple_health_records", sa.Column("double_support_pct", sa.Float(), nullable=True)
    )
    op.add_column("apple_health_records", sa.Column("walking_speed_kmh", sa.Float(), nullable=True))
    op.add_column("apple_health_records", sa.Column("respiratory_rate", sa.Float(), nullable=True))
    op.add_column(
        "apple_health_records", sa.Column("breathing_disturbances", sa.Float(), nullable=True)
    )
    op.add_column("apple_health_records", sa.Column("weight_kg", sa.Float(), nullable=True))
    op.add_column("apple_health_records", sa.Column("body_fat_pct", sa.Float(), nullable=True))
    op.add_column("apple_health_records", sa.Column("daylight_min", sa.Float(), nullable=True))
    op.create_index(
        op.f("ix_apple_health_records_entry_id"), "apple_health_records", ["entry_id"], unique=False
    )
    op.create_index(op.f("ix_extras_entry_id"), "extras", ["entry_id"], unique=False)
    op.create_index(
        op.f("ix_medication_records_entry_id"), "medication_records", ["entry_id"], unique=False
    )
    op.create_index(op.f("ix_mood_records_entry_id"), "mood_records", ["entry_id"], unique=False)
    op.create_index(
        op.f("ix_nutrition_records_entry_id"), "nutrition_records", ["entry_id"], unique=False
    )
    op.create_index(op.f("ix_pain_records_entry_id"), "pain_records", ["entry_id"], unique=False)
    op.create_index(
        op.f("ix_stress_records_entry_id"), "stress_records", ["entry_id"], unique=False
    )
    op.create_index(
        op.f("ix_weather_records_entry_id"), "weather_records", ["entry_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_weather_records_entry_id"), table_name="weather_records")
    op.drop_index(op.f("ix_stress_records_entry_id"), table_name="stress_records")
    op.drop_index(op.f("ix_pain_records_entry_id"), table_name="pain_records")
    op.drop_index(op.f("ix_nutrition_records_entry_id"), table_name="nutrition_records")
    op.drop_index(op.f("ix_mood_records_entry_id"), table_name="mood_records")
    op.drop_index(op.f("ix_medication_records_entry_id"), table_name="medication_records")
    op.drop_index(op.f("ix_extras_entry_id"), table_name="extras")
    op.drop_index(op.f("ix_apple_health_records_entry_id"), table_name="apple_health_records")
    op.drop_column("apple_health_records", "daylight_min")
    op.drop_column("apple_health_records", "body_fat_pct")
    op.drop_column("apple_health_records", "weight_kg")
    op.drop_column("apple_health_records", "breathing_disturbances")
    op.drop_column("apple_health_records", "respiratory_rate")
    op.drop_column("apple_health_records", "walking_speed_kmh")
    op.drop_column("apple_health_records", "double_support_pct")
    op.drop_column("apple_health_records", "walking_asymmetry_pct")
    op.drop_column("apple_health_records", "step_length_cm")
    op.drop_column("apple_health_records", "cardio_recovery")
    op.drop_column("apple_health_records", "vo2_max")
    op.drop_column("apple_health_records", "walking_hr_avg")
    op.drop_column("apple_health_records", "exercise_intensity")
    op.drop_column("apple_health_records", "resting_energy_kj")
    op.drop_column("apple_health_records", "flights_climbed")
    op.drop_column("apple_health_records", "distance_km")
    op.drop_column("apple_health_records", "sleep_rem_hours")
    op.drop_index(op.f("ix_activity_records_entry_id"), table_name="activity_records")
    op.drop_index(op.f("ix_workout_records_entry_id"), table_name="workout_records")
    op.drop_table("workout_records")
    op.drop_index(
        op.f("ix_nutrition_import_records_entry_id"), table_name="nutrition_import_records"
    )
    op.drop_table("nutrition_import_records")
    # ### end Alembic commands ###
