"""initial schema

Revision ID: 794f9d2b706f
Revises: 
Create Date: 2026-03-27 22:07:04.840987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '794f9d2b706f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_table('schema_fields',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('promoted_date', sa.Date(), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('field_name')
    )
    op.create_table('activity_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=True),
    sa.Column('pain_effect', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['daily_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('apple_health_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('sleep_hours', sa.Float(), nullable=True),
    sa.Column('sleep_quality', sa.Text(), nullable=True),
    sa.Column('resting_hr', sa.Integer(), nullable=True),
    sa.Column('hrv_ms', sa.Float(), nullable=True),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('active_calories', sa.Integer(), nullable=True),
    sa.Column('spo2_pct', sa.Float(), nullable=True),
    sa.Column('raw_data', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['daily_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extras',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('value_type', sa.String(length=20), nullable=False),
    sa.Column('first_seen', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['daily_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medication_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('dose', sa.String(length=100), nullable=True),
    sa.Column('time_taken', sa.String(length=10), nullable=True),
    sa.Column('effectiveness', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['daily_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mood_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('emotions', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['daily_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nutrition_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('meals', sa.Text(), nullable=True),
    sa.Column('alcohol', sa.Boolean(), nullable=True),
    sa.Column('caffeine_cups', sa.Integer(), nullable=True),
    sa.Column('water_liters', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['daily_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pain_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=50), nullable=False),
    sa.Column('intensity', sa.Integer(), nullable=False),
    sa.Column('pattern', sa.String(length=50), nullable=True),
    sa.Column('time_of_day', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['daily_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stress_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['daily_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weather_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('humidity_pct', sa.Float(), nullable=True),
    sa.Column('pressure_hpa', sa.Float(), nullable=True),
    sa.Column('pressure_change_hpa', sa.Float(), nullable=True),
    sa.Column('conditions', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['daily_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather_records')
    op.drop_table('stress_records')
    op.drop_table('pain_records')
    op.drop_table('nutrition_records')
    op.drop_table('mood_records')
    op.drop_table('medication_records')
    op.drop_table('extras')
    op.drop_table('apple_health_records')
    op.drop_table('activity_records')
    op.drop_table('schema_fields')
    op.drop_table('daily_entries')
    # ### end Alembic commands ###
