"""add day_type to daily_entries

Revision ID: 913af3612ea7
Revises: ba87db08cdf0
Create Date: 2026-04-02 11:45:46.088006

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "913af3612ea7"
down_revision: str | Sequence[str] | None = "ba87db08cdf0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("daily_entries", sa.Column("day_type", sa.String(length=20), nullable=True))
    # NOTE: stress_source VARCHAR(50)→String(200) skipped — SQLite ignores string length
    # ### end Alembic commands ###

    # Backfill day_type from stored date: 0=Sunday, 6=Saturday in SQLite
    conn = op.get_bind()
    conn.execute(
        sa.text(
            "UPDATE daily_entries SET day_type = CASE "
            "WHEN strftime('%w', date) IN ('0', '6') THEN 'weekend' "
            "ELSE 'workday' "
            "END "
            "WHERE day_type IS NULL"
        )
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("daily_entries", "day_type")
    # ### end Alembic commands ###
