"""add stretching boolean to daily_entries

Revision ID: b13e083e480a
Revises: 6ff20dd30eda
Create Date: 2026-03-29 20:07:04.830990

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b13e083e480a"
down_revision: str | Sequence[str] | None = "6ff20dd30eda"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("daily_entries", sa.Column("stretching", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("daily_entries", "stretching")
    # ### end Alembic commands ###
